name: Run Script

on:
  schedule:
    - cron: '30 5 * * *'  # Run every day at 5.30 UTC
  workflow_dispatch:  # Manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python main.py  
      
    - name: Delete xlsx file
      run: rm birthdays.xlsx

    - name: Commit and push changes
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Update TXT files"
        git push
